 steps:
  # Building front end
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', './', '--platform', 'linux/amd64', '-t', 'gcr.io/$PROJECT_ID/production:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/production:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'production', '--image', 'gcr.io/$PROJECT_ID/production:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/production:$COMMIT_SHA'
